Repository rtCamp/rtMedia, pull requests merged in 2022-02, with the labels that each got.

#1825 Fixed issue of media tab is not showing in groups page
  app/main/controllers/template/RTMediaNav.php
Labels: Tested

#1813 Fixed console js issues on settings page
  app/admin/RTMediaAdmin.php
Labels: Tested

#1821 Kamal issue #1820 [ rtMedia Restriction ] - When upper limit is reached for album creation, no warning message is displayed
  app/admin/RTMediaAdmin.php
  app/main/controllers/template/rtmedia-actions.php
  app/main/controllers/template/rtmedia-functions.php
Labels: Tested

#1819 Fixes issue 1816 - display update notice for rtmedia pro
  app/admin/RTMediaAdmin.php
Labels: on-hold

#1828 fixes issue 1827 - fav album height not working properly
  app/main/RTMedia.php
Labels: Ready For QA

#1841 fixes issue #1840 - total track number not saving or displaying issue
  app/main/controllers/media/RTMediaTags.php
Labels: Tested

#1846 fixes issue 1837 - rating issue when album is added
  .github/ci/main.sh
  .github/workflows/codeception.yml
  app/assets/js/rtMedia.js
  app/assets/js/rtmedia.min.js
  app/main/controllers/template/rtmedia-functions.php
Labels: Tested
